check_interval: 90  # 检查间隔（秒）

DNS:
  Domain_and_RR:
    - fleet42.xyz:  # 域名
        - cryptic
        - demo
        - codesifu
        - home
        - coderunner
#        - test  # 主机记录
    - 1wdbz.com:
        - emby
        - cloud
#        - codesifu.cn:
#        - '@'
    - codesifu.cn:
        - cook
    - ai-expert.cc:
        - demo
RDS:
  AutoUpdate:  # 自动定时更新配置
    ArrayName: home  # 白名单分组名称（要提前创建好）
    DBInstanceIds: &all_instance  # 要修改的RDS实例ID
      - rm-j6c1b69x1o7vyz682
  ManualUpdate:  # 手动更新配置
    ArrayName: my
    DBInstanceIds: # 要修改的RDS实例ID
      *all_instance

IPCheckList:  # 查看本机公网IP的网址
  - http://whatismyip.akamai.com/
  - https://ip.clang.cn/
  - http://icanhazip.com
  - https://ipecho.net/plain
  - https://tnx.nl/ip
  - https://www.trackip.net/ip
  - http://ip.cip.cc/

PushDeer:  # 给手机发推送通知用的，可忽略（需自行删除两行代码）
  key:
    network: PDU16135T20HQSDpgjBbDXjurBnRQ8mAOAcNDnSrk

log:  # 日志存放位置（会自动创建相应目录）
  path_dir: ~/log/aliyun-update-security-ips
  path_info: ~/log/aliyun-update-security-ips/info
  path_err: ~/log/aliyun-update-security-ips/err

